---
- name: Create Duckdns Directories
  file:
    path: "{{ item }}"
    state: directory
    # mode: 0755
  with_items:
    - "{{ docker_home }}/duckdns/config"

- name: Duckdns Docker Container
  docker_container:
    name: duckdns
    image: linuxserver/duckdns
    pull: true
    volumes:
      - "{{ duckdns_config_directory }}:/config:rw"
    env:
      TZ: "{{ ansible_nas_timezone }}"
      PUID: "{{ duckdns_user_id }}"
      PGID: "{{ duckdns_group_id }}"
      LOG_FILE: true #optional
      SUBDOMAINS: "{{ duckdns_SUBDOMAINS }}"
      TOKEN: "{{ duckdns_token }}"
    restart_policy: unless-stopped
    memory: 1g

